import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import apiRequest from '../api/client';

export default function Login() {
  const navigate = useNavigate(); const [phone, setPhone] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function handleSubmit(e) { e.preventDefault(); setError(''); setLoading(true); try { const data = await apiRequest('/auth/login', { method: 'POST', body: { phone, password } }); localStorage.setItem('agriaid_token', data.token); navigate('/dashboard'); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  return <div className="auth-page"><section className="auth-showcase" aria-hidden="true"><div className="auth-showcase-brand"><span>✦</span> agriaid</div><div className="auth-orbit auth-orbit--one" /><div className="auth-orbit auth-orbit--two" /><div className="auth-showcase-copy"><div className="auth-kicker">MADE FOR THE FIELD</div><h1>Your farm network, always close by.</h1><p>Manage bookings, support and services from one calm, simple place.</p></div><div className="auth-field-art">🌾</div></section><main className="auth-panel"><div className="auth-form-wrap auth-form-wrap--login"><Link className="auth-brand" to="/"><span>✦</span> agriaid</Link><div className="auth-heading"><div className="auth-kicker">WELCOME BACK</div><h1>Good to see you.</h1><p>Log in to continue to your AgriAid account.</p></div><form onSubmit={handleSubmit}><div className="field"><label className="field-label" htmlFor="phone">Phone</label><input id="phone" className="input" inputMode="tel" value={phone} onChange={(e) => setPhone(e.target.value)} required /></div><div className="field"><label className="field-label" htmlFor="password">Password</label><input id="password" className="input" type="password" value={password} onChange={(e) => setPassword(e.target.value)} required /></div>{error && <p className="alert alert-error">{error}</p>}<button type="submit" className="btn btn-primary btn-block" disabled={loading}>{loading ? 'Logging in…' : 'Log in'}</button></form><p className="helper-text auth-footer">New here? <Link to="/register">Create an account</Link></p></div></main></div>;
}
